const PIN_WIDTH = 50;
const PIN_HEIGHT = 70;
const OFFER_PHOTO_WIDTH = 40;
const OFFER_PHOTO_HEIGHT = 45;
const OFFER_PHOTO_ALT = 'Фотография жилья';

export { PIN_WIDTH, PIN_HEIGHT, OFFER_PHOTO_WIDTH, OFFER_PHOTO_HEIGHT, OFFER_PHOTO_ALT };
